name: Upload

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: devops
        path: |
          devops.py
          templates/
          static/
  deployment:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: devops
      - name: Mostrar arquivos
        run: ls -R
